#pragma once

// ============================================================
//  inference.h
//  Interface for the TensorFlow Lite Micro 1D-CNN drop detector.
//
//  HOW TFLITE MICRO WORKS ON THE PICO
//  ------------------------------------
//  TFLite Micro is a stripped-down inference engine designed for
//  microcontrollers. Instead of loading a model from a filesystem
//  at runtime, the model is compiled directly into firmware as a
//  C byte array (model_data.cc, generated by xxd). The engine
//  then interprets this flatbuffer in-place — no dynamic linking,
//  no OS, no heap allocation beyond a statically-sized tensor
//  arena you provide.
//
//  The "tensor arena" is a raw byte buffer you carve out of RAM.
//  TFLite Micro uses it for all intermediate tensors during
//  inference. If the arena is too small, invoke() will return
//  kTfLiteError — increase TENSOR_ARENA_SIZE if that happens.
//
//  EXPECTED MODEL CONTRACT (agree with Asrith before training):
//    Input:  float32 tensor, shape [1, WINDOW_SIZE_SAMPLES, 3]
//            (batch=1, timesteps=50, channels=ax/ay/az)
//    Output: float32 tensor, shape [1, 2]
//            index 0 = probability of "normal"
//            index 1 = probability of "drop"
//  Confidence score returned by infer_run() is output[1].
// ============================================================

#include <stdint.h>
#include <stdbool.h>
#include "config.h"

// Tensor arena size in bytes. The RP2350 has 520KB of RAM (vs 264KB on
// RP2040), so we can afford a generous arena. 64KB comfortably fits a
// small-to-medium 1D CNN and leaves plenty of RAM for the IMU buffers,
// the HTTP server, and the Wi-Fi stack. Increase further if needed.
#define TENSOR_ARENA_SIZE (64 * 1024)

// ---- Lifecycle ----

/**
 * infer_init()
 * Allocates the tensor arena, loads the embedded model, resolves
 * the op kernels the model uses, and allocates tensors.
 * Returns true on success. Call once in setup() after imu_init().
 *
 * If this returns false, check serial output — it will tell you
 * whether the arena was too small or the model flatbuffer was
 * corrupt (e.g., xxd conversion went wrong).
 */
bool infer_init();

// ---- Inference ----

/**
 * infer_run(inputData, outConfidence)
 * Copies inputData (INPUT_TENSOR_SIZE floats) into the model's
 * input tensor, runs inference, and writes the drop-class
 * probability into *outConfidence.
 *
 * Returns true if inference succeeded. A confidence > the
 * ANOMALY_CONFIDENCE_THRESHOLD constant means a drop was detected.
 *
 * This call blocks for the duration of inference — typically
 * 5–20 ms on a Pico 2W for a small 1D CNN. Design your loop()
 * so time-sensitive operations (UDP listening) can still run.
 */
bool infer_run(const float inputData[INPUT_TENSOR_SIZE],
               float* outConfidence);
