// ============================================================
//  inference.cpp
//  TFLite Micro inference engine setup and run loop.
//
//  IMPORTANT — BEFORE THIS COMPILES:
//  1. Ask Asrith to train the model and convert it:
//       python -c "import tensorflow as tf; converter = tf.lite.TFLiteConverter.from_saved_model('model/'); tflite_model = converter.convert(); open('model.tflite','wb').write(tflite_model)"
//     Then convert to a C array:
//       xxd -i model.tflite > src/model_data.cc
//     Then add this to the top of model_data.cc:
//       #include "model_data.h"
//     And make sure model_data.h declares:
//       extern const unsigned char model_tflite[];
//       extern const unsigned int model_tflite_len;
//
//  2. Add the TFLite Micro source to lib/tflite-micro/.
//     The required files are listed in the README.
//
//  3. Confirm the model's input/output shapes match the contract
//     described in inference.h before running on hardware.
// ============================================================

#include "inference.h"
#include "model_data.h"  // generated by xxd — contains the model byte array
#include <Arduino.h>
#include <string.h>

// TFLite Micro headers — these come from the lib/tflite-micro/ folder.
// The exact include paths depend on how you structure the library.
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

// ---- TFLite Micro objects ----
// These are allocated statically — no heap allocation occurs.
// TFLite Micro is specifically designed to avoid malloc/free so
// it works reliably on microcontrollers without an OS allocator.

// The tensor arena: a raw byte buffer TFLite uses as its scratchpad.
// All intermediate tensors live here during inference.
static uint8_t tensorArena[TENSOR_ARENA_SIZE];

// Op resolver: tells TFLite Micro which kernel implementations to
// include. Only register ops your model actually uses — each
// registered op adds flash and RAM overhead.
// Check your model's ops with: python -m tflite.tool_api.flatbuffers_info model.tflite
static tflite::MicroMutableOpResolver<6> opResolver;

static const tflite::Model*      model       = nullptr;
static tflite::MicroInterpreter* interpreter = nullptr;
static TfLiteTensor*             inputTensor = nullptr;
static TfLiteTensor*             outputTensor = nullptr;

// ============================================================
//  infer_init
// ============================================================
bool infer_init() {
    // ---- 1. Load the model flatbuffer ----
    // model_tflite[] is the byte array generated by xxd.
    // GetModel() just reads the magic number and version —
    // it doesn't copy anything, which is why TFLite Micro is
    // so memory-efficient: the model stays in flash read-only.
    model = tflite::GetModel(model_tflite);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.print("[INFER] ERROR: Model schema version mismatch. "
                     "Expected ");
        Serial.print(TFLITE_SCHEMA_VERSION);
        Serial.print(", got ");
        Serial.println(model->version());
        return false;
    }

    // ---- 2. Register op kernels ----
    // These must match the layers Asrith used when building the model.
    // A typical 1D CNN for time-series will use Conv2D (or DepthwiseConv2D),
    // Reshape, FullyConnected, Relu, and Softmax.
    opResolver.AddConv2D();
    opResolver.AddDepthwiseConv2D();
    opResolver.AddReshape();
    opResolver.AddFullyConnected();
    opResolver.AddRelu();
    opResolver.AddSoftmax();
    // Add more ops here if the model uses them (e.g., AddMaxPool2D).

    // ---- 3. Build the interpreter ----
    static tflite::MicroInterpreter staticInterpreter(
        model, opResolver, tensorArena, TENSOR_ARENA_SIZE);
    interpreter = &staticInterpreter;

    // ---- 4. Allocate tensors in the arena ----
    TfLiteStatus allocStatus = interpreter->AllocateTensors();
    if (allocStatus != kTfLiteOk) {
        Serial.println("[INFER] ERROR: AllocateTensors() failed. "
                       "Increase TENSOR_ARENA_SIZE in inference.h.");
        return false;
    }

    // ---- 5. Cache pointers to the I/O tensors ----
    inputTensor  = interpreter->input(0);
    outputTensor = interpreter->output(0);

    // ---- 6. Validate tensor shapes against our contract ----
    // Expected input: float32, shape [1, WINDOW_SIZE_SAMPLES, 3]
    if (inputTensor->dims->size != 3 ||
        inputTensor->dims->data[1] != WINDOW_SIZE_SAMPLES ||
        inputTensor->dims->data[2] != 7) {
        Serial.println("[INFER] ERROR: Input tensor shape mismatch. "
                       "Expected [1,50,7]. Check model training script.");
        return false;
    }

    Serial.print("[INFER] TFLite Micro online. Arena used: ");
    Serial.print(interpreter->arena_used_bytes());
    Serial.println(" bytes.");
    return true;
}

// ============================================================
//  infer_run
// ============================================================
bool infer_run(const float inputData[INPUT_TENSOR_SIZE],
               float* outConfidence) {
    // ---- 1. Copy flattened IMU window into input tensor ----
    // inputTensor->data.f points directly into the tensor arena.
    // We write the flat [ax0,ay0,az0, ax1,ay1,az1, ...] array
    // straight into it — no intermediate buffer needed.
    memcpy(inputTensor->data.f, inputData,
           INPUT_TENSOR_SIZE * sizeof(float));

    // ---- 2. Run inference ----
    TfLiteStatus invokeStatus = interpreter->Invoke();
    if (invokeStatus != kTfLiteOk) {
        Serial.println("[INFER] ERROR: Invoke() failed.");
        return false;
    }

    // ---- 3. Read the output ----
    // outputTensor->data.f[0] = P(normal)
    // outputTensor->data.f[1] = P(drop)   ← this is our confidence score
    *outConfidence = outputTensor->data.f[1];

    Serial.print("[INFER] Drop confidence: ");
    Serial.println(*outConfidence, 3);

    return true;
}
