#include "inference.h"
#include "model_data.h"  // generated by xxd — contains the model byte array
#include <Arduino.h>
#include <string.h>

#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "tensorflow/lite/schema/schema_generated.h"

static uint8_t tensorArena[TENSOR_ARENA_SIZE];

static tflite::MicroMutableOpResolver<6> opResolver;

static const tflite::Model*      model       = nullptr;
static tflite::MicroInterpreter* interpreter = nullptr;
static TfLiteTensor*             inputTensor = nullptr;
static TfLiteTensor*             outputTensor = nullptr;

bool infer_init() {
    model = tflite::GetModel(model_tflite);
    if (model->version() != TFLITE_SCHEMA_VERSION) {
        Serial.print("[INFER] ERROR: Model schema version mismatch. "
                     "Expected ");
        Serial.print(TFLITE_SCHEMA_VERSION);
        Serial.print(", got ");
        Serial.println(model->version());
        return false;
    }

    opResolver.AddConv2D();
    opResolver.AddDepthwiseConv2D();
    opResolver.AddReshape();
    opResolver.AddFullyConnected();
    opResolver.AddRelu();
    opResolver.AddSoftmax();

    static tflite::MicroInterpreter staticInterpreter(
        model, opResolver, tensorArena, TENSOR_ARENA_SIZE);
    interpreter = &staticInterpreter;

    TfLiteStatus allocStatus = interpreter->AllocateTensors();
    if (allocStatus != kTfLiteOk) {
        Serial.println("[INFER] ERROR: AllocateTensors() failed. "
                       "Increase TENSOR_ARENA_SIZE in inference.h.");
        return false;
    }

    inputTensor  = interpreter->input(0);
    outputTensor = interpreter->output(0);

    if (inputTensor->dims->size != 3 ||
        inputTensor->dims->data[1] != WINDOW_SIZE_SAMPLES ||
        inputTensor->dims->data[2] != 3) {
        Serial.println("[INFER] ERROR: Input tensor shape mismatch. "
                       "Check model training script.");
        return false;
    }

    Serial.print("[INFER] TFLite Micro online. Arena used: ");
    Serial.print(interpreter->arena_used_bytes());
    Serial.println(" bytes.");
    return true;
}

bool infer_run(const float inputData[INPUT_TENSOR_SIZE],
               float* outConfidence) {

    memcpy(inputTensor->data.f, inputData,
           INPUT_TENSOR_SIZE * sizeof(float));

    TfLiteStatus invokeStatus = interpreter->Invoke();
    if (invokeStatus != kTfLiteOk) {
        Serial.println("[INFER] ERROR: Invoke() failed.");
        return false;
    }

    *outConfidence = outputTensor->data.f[1];

    Serial.print("[INFER] Drop confidence: ");
    Serial.println(*outConfidence, 3);

    return true;
}