#pragma once
#include <stddef.h>
#include <stdbool.h>

// Load TFLite model. Returns false on failure.
// model_data and model_len come from model_data.cc (generated by Asrith).
bool infer_init(const unsigned char *model_data, size_t model_len);

// Run inference on a pre-flattened float[350] window.
// Sets g_lastConfidence (P(drop)) and returns it.
// Returns -1.0f on error.
float infer_run(const float *window_flat);

// P(drop) from the last successful inference run.
extern float g_lastConfidence;