/*
 * SwarmVerifier — Transporter Firmware
 * Board: Raspberry Pi Pico 2W (RP2350)
 *
 * State machine:
 *   IDLE → (TFLite P(drop) >= 0.85) → ANOMALY
 *   ANOMALY → (quorum selected) → DELIVERING
 *   DELIVERING → (all served or timeout) → IDLE
 */

#include <Arduino.h>
#include <WiFi.h>
#include <ArduinoJson.h>
#include <cstddef>
#include <uECC.h>

#include "config.h"
#include "crypto.h"
#include "imu.h"
#include "inference.h"
#include "network.h"
#include "gateway.h"

// ── Model data (generated by: xxd -i model.tflite > src/model_data.cc) ────────
// Uncomment when model_data.cc is delivered by Asrith.
extern const unsigned char model_tflite[];
extern const unsigned int  model_tflite_len;

// ── Global identity ───────────────────────────────────────────────────────────
uint8_t g_privKey[PRIVKEY_BYTES];
uint8_t g_pubKey[PUBKEY_BYTES];
char    g_pubHex[PUBKEY_HEX_LEN + 1];

// ── Global event state ────────────────────────────────────────────────────────
char         g_currentEventId[256];   // submission_sig hex — used by network.cpp
SystemState  g_systemState = STATE_IDLE;

// ── Timing ────────────────────────────────────────────────────────────────────
static uint32_t _lastSampleMs    = 0;
static uint32_t _lastInferMs     = 0;
static uint32_t _anomalyStartMs  = 0;
static uint32_t _deliveryStartMs = 0;

// ── Submission signature builder ──────────────────────────────────────────────
// submission_sig = ECDSA_sign(SHA-256(canonical_json))
// Acts as the unique event ID on the Flow contract.
static void _build_submission_sig(float conf, char *out_hex) {
    char canonical[1024];
    // Include sorted quorum IDs
    // For simplicity we iterate quorum in insertion order (already scored/ranked)
    int len = snprintf(canonical, sizeof(canonical),
        "{\"anomaly_confidence\":%.4f,\"quorum_ids\":[", conf);
    for (int i = 0; i < g_quorumSize; i++) {
        len += snprintf(canonical + len, sizeof(canonical) - len,
            "%s\"%s\"", i > 0 ? "," : "", g_quorum[i].pubkey_hex);
    }
    snprintf(canonical + len, sizeof(canonical) - len,
        "],\"timestamp_ms\":%lu,\"transporter_pubkey\":\"%s\"}",
        (unsigned long)millis(), g_pubHex);

    uint8_t sig[SIG_BYTES];
    crypto_sign(g_privKey, (const uint8_t *)canonical, strlen(canonical), sig);
    bytes_to_hex(sig, SIG_BYTES, out_hex);
}

// ── ANOMALY event cycle ───────────────────────────────────────────────────────
static void _run_anomaly_cycle() {
    Serial.printf("\n[Main] ANOMALY detected  conf=%.4f\n", g_lastConfidence);

    // 1. Snapshot CSV buffer before sending anomaly broadcast
    imu_buildCsvBuffer(g_csvBuffer, sizeof(g_csvBuffer));

    // 2. Upload CSV to Storacha
    //    (skipped in simulation mode — gateway returns fake CID)
    char cid[128] = "";
    if (!gateway_storacha_upload(g_csvBuffer, cid, sizeof(cid))) {
        Serial.println("[Main] Storacha pre-upload skipped — will upload post-consensus");
        // cid stays empty, filled in after finalizeEvent
    }

    // 3. Broadcast PKT_ANOMALY
    net_sendAnomaly(g_lastConfidence);
    g_systemState    = STATE_ANOMALY;
    g_collectingBids = true;
    g_bidCount       = 0;

    Serial.printf("[Main] Bid window open (%d ms)...\n", BID_WINDOW_MS);
}

// ── After bid window closes ───────────────────────────────────────────────────
static void _close_bid_window() {
    g_collectingBids = false;
    Serial.printf("[Main] Bid window closed. bidCount=%d auditorCount=%d\n", 
                  g_bidCount, g_auditorCount);
    if (g_bidCount == 0) {
        Serial.println("[Main] No bids — returning to IDLE");
        g_systemState = STATE_IDLE;
        return;
    }

    // Query Flow stake/reputation for each bidder (no-op when FLOW_ENABLED=0)
    for (int i = 0; i < g_bidCount; i++) {
        gateway_query_node(g_bidPool[i].pubkey_hex,
                           &g_bidPool[i].stake, &g_bidPool[i].rep);
    }

    // Score and select quorum
    int selected = net_selectQuorum(g_pubHex);
    if (selected == 0) {
        Serial.println("[Main] No eligible quorum — returning to IDLE");
        g_systemState = STATE_IDLE;
        return;
    }

    // Build submission_sig (unique event ID)
    _build_submission_sig(g_lastConfidence, g_currentEventId);
    Serial.printf("[Main] event_id=%.24s...\n", g_currentEventId);

    // Phase 1: register anomaly on Flow contract
    const char *quorum_ids[QUORUM_SIZE];
    for (int i = 0; i < g_quorumSize; i++) quorum_ids[i] = g_quorum[i].pubkey_hex;
    gateway_register_anomaly(g_pubHex, g_currentEventId, g_lastConfidence,
                             quorum_ids, g_quorumSize, 1.0f);

    // Send PKT_QUORUM to each selected auditor
    for (int i = 0; i < g_quorumSize; i++) {
        net_sendQuorumNotify(&g_quorum[i]);
    }

    g_systemState    = STATE_DELIVERING;
    _deliveryStartMs = millis();
    Serial.printf("[Main] Delivering to %d auditor(s)...\n", g_quorumSize);
}

// ── After delivery window closes ──────────────────────────────────────────────
static void _close_delivery_window() {
    Serial.println("[Main] Delivery window closed — returning to IDLE");

    // In production: wait for AnomalySettled event from Flow, then upload bundle
    // to Storacha and call gateway_update_event_cid(). For demo this is simulated.
    char final_cid[128] = "bafyreiSIMULATED_FINAL";
    gateway_update_event_cid(g_currentEventId, final_cid);

    // Reset per-event state
    g_quorumSize = 0;
    memset(g_nonces, 0, sizeof(g_nonces));
    g_systemState = STATE_IDLE;
}

// ── Arduino setup ─────────────────────────────────────────────────────────────
void setup() {
    Serial.begin(115200);
    delay(1500);
    Serial.println("\n=== SwarmVerifier Transporter ===");

    // ── Crypto: key generation ────────────────────────────────────────────────
    crypto_init();
    // Load pre-generated key so Flow account stays consistent across reboots
    const char *priv_hex = PICO_PRIV_KEY_HEX;
    if (!hex_to_bytes(priv_hex, 64, g_privKey)) {
        Serial.println("[FATAL] Failed to decode private key from build flag");
        while (1) delay(1000);
    }
    // Derive public key from private key
    uECC_compute_public_key(g_privKey, g_pubKey, uECC_secp256r1());
    bytes_to_hex(g_pubKey, PUBKEY_BYTES, g_pubHex);
    Serial.printf("[Crypto] pubkey=%s...\n", g_pubHex + PUBKEY_HEX_LEN - 24);

    // ── IMU ───────────────────────────────────────────────────────────────────
    if (!imu_init()) {
        Serial.println("[FATAL] IMU init failed");
        while (1) delay(1000);
    }

    // ── TFLite  ───────────────────────────────────────────────────────────────
    if (!infer_init(model_tflite, model_tflite_len)) {
        Serial.println("[WARN] TFLite init failed — inference disabled");
    }

    // ── WiFi ──────────────────────────────────────────────────────────────────
    Serial.printf("[WiFi] Connecting to %s...\n", WIFI_SSID);
    WiFi.begin(WIFI_SSID, WIFI_PASS);
        // Add right after WiFi.begin succeeds
    WiFi.setDNS(IPAddress(8,8,8,8), IPAddress(8,8,4,4));
    delay(500);
    int attempts = 0;
    while (WiFi.status() != WL_CONNECTED && attempts < 40) {
        delay(500); Serial.print("."); attempts++;
    }
    if (WiFi.status() != WL_CONNECTED) {
        Serial.println("\n[FATAL] WiFi connection failed");
        while (1) delay(1000);
    }
    Serial.printf("\n[WiFi] Connected. IP=%s\n", WiFi.localIP().toString().c_str());

    // ── Network ───────────────────────────────────────────────────────────────
    if (!net_init()) {
        // Starts up 2 UDP ports, one for anomaly/beacon and one for bids, and an HTTP server for auditors to fetch CSV+payload
        Serial.println("[FATAL] Network init failed");
        while (1) delay(1000);
    }

        // DNS test — add after net_init()
    IPAddress flowIP;
    if (WiFi.hostByName("rest-testnet.onflow.org", flowIP)) {
        Serial.printf("[DNS] rest-testnet.onflow.org = %s\n", flowIP.toString().c_str());
    } else {
        Serial.println("[DNS] FAILED to resolve rest-testnet.onflow.org");
    }

    Serial.println("[Main] Ready. Sampling IMU at 50 Hz...\n");
    gateway_init(g_privKey);
}

// ── Arduino loop ──────────────────────────────────────────────────────────────
void loop() {
    uint32_t now = millis();

    // ── 1. IMU sampling at 50 Hz ──────────────────────────────────────────────
    if (now - _lastSampleMs >= (1000 / SAMPLE_RATE_HZ)) {
        _lastSampleMs = now;
        imu_update();
    }

    // ── 2. TFLite inference at 1 Hz ───────────────────────────────────────────
    if (now - _lastInferMs >= 1000 && g_systemState == STATE_IDLE) {
        _lastInferMs = now;

        float window[INPUT_TENSOR_SIZE];
        imu_flattenWindow(window);

        float conf = infer_run(window);
        if (conf < 0) {
            // Model not loaded — skip
        } else if (conf >= ANOMALY_CONFIDENCE_THRESHOLD) {
            _run_anomaly_cycle();
            _anomalyStartMs = now;
        }
    }

    // ── 3. UDP polling ────────────────────────────────────────────────────────
    // Around the net_handleUdp call, add a periodic log
    static uint32_t _lastUdpLogMs = 0;
    if (g_collectingBids && now - _lastUdpLogMs >= 1000) {
        _lastUdpLogMs = now;
        Serial.printf("[Main] Collecting bids... bidCount=%d\n", g_bidCount);
    }
    net_handleUdp();


    // ── 4. HTTP client serving ────────────────────────────────────────────────
    if (g_systemState == STATE_DELIVERING) {
        net_handleHttp();
    }

    // ── 5. State machine transitions ──────────────────────────────────────────
    switch (g_systemState) {
        case STATE_ANOMALY:
            // Close bid window after BID_WINDOW_MS
            if (now - _anomalyStartMs >= BID_WINDOW_MS) {
                _close_bid_window();
            }
            break;

        case STATE_DELIVERING:
            // Timeout after DELIVERY_TIMEOUT_MS regardless of how many auditors responded
            if (now - _deliveryStartMs >= DELIVERY_TIMEOUT_MS) {
                _close_delivery_window();
            }
            break;

        case STATE_IDLE:
        default:
            break;
    }
}